---
logging:
  level: INFO
  loggers:
    com.acrolinx: DEBUG

mongodb:
  uri: mongodb://admin:password@localhost:27017
#  uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017
  database: warehouse

redis:
  host: localhost
#  host: ${REDIS_HOST}
  port: 6379
